typography_spectrum: 0.7930442248674866
color:
  brandColors:
    - '#FFF5F3'
    - '#0E080A'
    - '#E0AE00'
    - '#CBD5D7'
    - '#925320'
  brandStrength: 0.8021016984039199
  lightness: 0.354154858983924
  saturation: 0.0546646999711595
  rhythmicContrast: 0.49806248949213633
layout_spectrum: 0.6806308369753459
author:
  name: Brady Mckenna
  email: mckmuze@gmail.com
name: Mckmuze
navigation:
  - name: VR performances
    url: 'https://www.youtube.com/user/Mckmuze'
    type: external
  - name: Music
    id: b34364e9-e78f-4078-8751-a439e533e915
    type: content
  - name: About
    id: 74184c8b-d5f4-45e8-b985-0c275849a8e8
    type: content
title: Mckmuze
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2b2f9aff-5050-4303-94d4-421f35694f42.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2b2f9aff-5050-4303-94d4-421f35694f42.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Musician/Songwriter | VR Performer
purpose:
  - type: internal
    label: Show Schedule
    item: 1c829aef-bf6a-4983-af86-43e8b43c9e88
github: true
